version: '3.8'
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:80"
    networks:
      - touchless_network

  server:
    build:
      context: ./server
    ports:
      - "3001:3001"
    networks:
      - touchless_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - client
      - server
    networks:
      - touchless_network

networks:
  touchless_network:
    driver: bridge
